
exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('scraps').del()
    .then(function () {
      // Inserts seed entries
      return knex('scraps').insert([
        {
          id: 1,
          scrap_name: 'Hot Chips',
          category: 'Food',
          description: 'Very Hot Chips, but they are half eaten',
          address: '126 Austin Street, Mount Victoria, Wellington, New Zealand',
          latitude: -41.298736572265625,
          longitude: 174.78701782226562,
          user_id: 1,
        },
        {
          id: 2,
          scrap_name: 'Banana',
          category: 'Food',
          description: 'Green Banana (the best)',
          address: 'Bohemein, Featherston Street, Wellington Central, Wellington, Wellington City, Wellington, 6145, New Zealand',
          latitude: -41.2819967,
          longitude: 174.7779542,
          user_id: 1,
        },
        {
          id: 3,
          scrap_name: 'Couch',
          category: 'Furniture',
          description: '50 year old couch - mint condition',
          address: '78 Pirie Street, Mount Victoria, Wellington, New Zealand',
          latitude: -41.29813766479492,
          longitude: 174.78538513183594,
          user_id: 2,
        },
        {
          id: 4,
          scrap_name: 'Basketball Hoop',
          category: 'Furniture',
          description: 'Basketball Hoop - only used once',
          address: 'Caci, Oriental Parade, Oriental Bay, Wellington, Wellington City, Wellington, 6011, New Zealand',
          latitude: -41.2914082,
          longitude: 174.7943709,
          user_id: 6,
        },
        {
          id: 5,
          scrap_name: 'Soccer Ball',
          category: 'Stuff',
          description: 'Soccer Ball, the best soccer ball of all time',
          address: 'Plumbing World, Abel Smith Street, Mount Cook, Wellington, Wellington City, Wellington, 6040, New Zealand',
          latitude: -41.29696455,
          longitude: 174.77528781,
          user_id: 5,
        },
        {
          id: 6,
          scrap_name: 'Apple',
          category: 'Food',
          description: 'Half eaten apple',
          address: 'Dakota, 74, Courtenay Place, Wellington, Wellington City, Wellington, 6011, New Zealand',
          latitude: -41.2930544,
          longitude: 174.7804585,
          user_id: 4,
        },
        {
          id: 7,
          scrap_name: 'Burger',
          category: 'Food',
          description: 'Garlic Burger, disguisting',
          address: 'Worldwide Backpackers, 291, The Terrace, Aro Valley, Wellington, Wellington City, Wellington, 6040, New Zealand',
          latitude: -41.2911798,
          longitude: 174.771028,
          user_id: 3,
        },
        {
          id: 8,
          scrap_name: 'Pool Table',
          category: 'Furniture',
          description: 'Nice one',
          address: 'Museum of New Zealand Te Papa Tongarewa, Cable Street, Te Aro, Wellington, 6011, New Zealand',
          latitude: -41.2903293,
          longitude: 174.78192779,
          user_id: 4,
        },
        {
          id: 9,
          scrap_name: 'Chilli Coffee',
          category: 'Food',
          description: 'Half Coffee, Half Chilli - it is hot',
          address: 'The Lobby, 100, Willis Street, Te Aro, Wellington, 6040, New Zealand',
          latitude: -41.28762235,
          longitude: 174.7736755,
          user_id: 5,
        },
        {
          id: 10,
          scrap_name: 'TV',
          category: 'Stuff',
          description: 'Smol TV',
          address: 'Noel Leeming, 133-139, Tory Street, Te Aro, Wellington, Wellington City, Wellington, 6011, New Zealand',
          latitude: -41.29717515,
          longitude: 174.78023297,
          user_id: 6,
        },
        {
          id: 11,
          scrap_name: 'Sweater',
          category: 'Clothes',
          description: 'Striped and Freddy Kreuger-esque',
          address: '50 Oriental Parade, Oriental Bay, Wellington, New Zealand',
          latitude: -41.29132080078125,
          longitude: 174.7928009033203,
          user_id: 5,
        },
        {
          id: 12,
          scrap_name: 'Ollie\'s bike',
          category: 'Stuff',
          description: 'Not needed for the foreseeable future',
          address: '25 Hawker Street, Mount Victoria, Wellington, New Zealand',
          latitude: -41.293270111083984,
          longitude: 174.78880310058594,
          user_id: 3,
        },
        {
          id: 13,
          scrap_name: 'Speedos',
          category: 'Clothes',
          description: 'Togs togs togs, undies',
          address: '200 Victoria Street, Te Aro, Wellington, New Zealand',
          latitude: -41.29350280761719,
          longitude: 174.77330017089844,
          user_id: 6,
        },
        {
          id: 14,
          scrap_name: 'G-string',
          category: 'Clothes',
          description: 'Realise your buttcheek tan',
          address: '30 Webb Street, Mount Cook, Wellington, New Zealand',
          latitude: -41.29744338989258,
          longitude: 174.77243041992188,
          user_id: 4,
        },
      ]);
    });
};
